### ISSUE TITLE
Failure to update items with files

### ISSUE THREAD

**Issue by HaddadJoe** [1Password/connect-sdk-python#57] opened 2022-12-11 22:11 UTC
### Your environment
SDK Version: 1.3.0
Connect Server Version: 1.5.7
OS: MacOS Montery 12.6
Python Version: 3.7.5

## What happened?
Updating an item that contains a file fails with error 
```
onepasswordconnectsdk.client.FailedToRetrieveItemException: Unable to post item. Received 400                    for /v1/vaults/********/items/***** with message: Validation: (validateVaultItem failed to Validate), Couldn't validate the item: "[ItemValidator] has found 1 errors, 0 warnings: \nErrors:{1. Field of unexpected type \"\" at \"item.details.documentAttributes\". Requires one of [\"object\"]}"
```

## What did you expect to happen?
After downloading the item be able to update it from the sdk

## Steps to reproduce
1. Create json document secret using the json below. I tried with different combinations all jsons break it for us.
2. run this code (silly code, update without any modification)
 ```
client_from_token: Client = new_client()
item_title = "your_item"
vault_title = "your_vault"
item = client_from_token.get_item(item_title, vault_title)
client_from_token.update_item(item.id, item.vault.id, item)
```

## Notes & Logs
had to zip, github does not allow json files uploads. [bla.json.zip](https://github.com/1Password/connect-sdk-python/files/10203407/bla.json.zip)

**Comment by HaddadJoe** [comment] 2022-12-19 21:21
Any feedback here @jpcoenen ? I'm happy to open PRs if you approve the issue

**Comment by jpcoenen** [comment] 2022-12-22 10:44
Hi @HaddadJoe,

The error returned here is not super helpful, but it comes from the fact that Connect does not yet support modifying or uploading files stored on 1Password (we want to add support for that in the future). That makes it difficult to update a Document item because that item basically represents a file. Nevertheless, the error returned is unhelpful; I will file an internal issue for that.

Could you share what it is that you want to change for the item: the file that is stored in the document or any of the other fields? I think the latter is easier to fix and might already be possible without a change to Connect.

**Comment by HaddadJoe** [comment] 2022-12-22 14:28
I'm just trying to change some of the other fields like tags and notes. I understand that files might be harder to handle but let's just return an exception when files are changed or just ignore that change(even though that might be tricky as the user would expect a change). The rest of the fields should be able to be editable.

**Comment by volodymyrZotov** [comment] 2022-12-29 12:39
Hi @HaddadJoe.
I was trying to reproduce the issue with the steps you provided, but could not.

Used:
SDK Version: 1.3.0
Connect Server Version: 1.5.7
Python Version: 3.7.5

I was able successfully to update an item with the file. 
Here is the code example
```
# example with updating title
item = client.get_item("Login1", "dev")
item.title = 'Login'
client.update_item(item.id, item.vault.id, item)

# example without modifying item
item = client.get_item("Login1", "dev")
client.update_item(item.id, item.vault.id, item)

# verify there is an item with file
file = client.get_files(item.id, item.vault.id)
print(file)

# it prints
[{'content_path': '/v1/vaults/<vauldId>/items/<itemId>/files/<fileId>/content',
 'id': 'fileId',
 'name': 'bla.json',
 'size': 32}]
```

Maybe there is something specific in your item, that prevents it from updating?

**Comment by volodymyrZotov** [comment] 2023-03-01 19:14
Hi @HaddadJoe. Is it still the case for you?

**Comment by HaddadJoe** [comment] 2023-03-03 15:29
We upgraded our op-connect server to the latest `1password/connect-sync:1.5.7` and ran the same code above, still getting the error on the update
```
from legalist.legalist.credentials.one_pass import client

item_title = "bla"
vault_title = "Engineering-Shared"
item = client.get_item(item_title, vault_title)
print(item.id)
client.update_item(item.id, item.vault.id, item)
```
here's the error, there was no update to the [python sdk](https://github.com/1Password/connect-sdk-python/) since then. I see a lot of commits but the team didn't cut a release yet 

```
Traceback (most recent call last):
  File "/Users/joehaddad/Library/Caches/pypoetry/virtualenvs/legalist-4Blx9NQP-py3.11/lib/python3.11/site-packages/onepasswordconnectsdk/client.py", line 286, in update_item
    response.raise_for_status()
  File "/Users/joehaddad/Library/Caches/pypoetry/virtualenvs/legalist-4Blx9NQP-py3.11/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://staging.1pass.legalist.com/v1/vaults/5owhekkdsih65suiisvfd37niq/items/4zajgalyrblts4ljdx72t7nxkm

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joehaddad/Desktop/legalist/legalist/local_testing.py", line 7, in <module>
    client.update_item(item.id, item.vault.id, item)
  File "/Users/joehaddad/Library/Caches/pypoetry/virtualenvs/legalist-4Blx9NQP-py3.11/lib/python3.11/site-packages/onepasswordconnectsdk/client.py", line 288, in update_item
    raise FailedToRetrieveItemException(
onepasswordconnectsdk.client.FailedToRetrieveItemException: Unable to post item. Received 400                    for /v1/vaults/5owhekkdsih65suiisvfd37niq/items/4zajgalyrblts4ljdx72t7nxkm with message: Validation: (validateVaultItem failed to Validate), Couldn't validate the item: "[ItemValidator] has found 1 errors, 0 warnings: \nErrors:{1. Field of unexpected type \"\" at \"item.details.documentAttributes\". Requires one of [\"object\"]}"

Process finished with exit code 1
```

**Comment by HaddadJoe** [comment] 2023-07-27 13:47
@volodymyrZotov any updates here?

**Comment by volodymyrZotov** [comment] 2023-08-08 16:48
Hi @HaddadJoe. Unfortunately, I didn't have a chance to try to reproduce it once again. But this issue is on the our team's radar and we'll back on that soon.

**Comment by volodymyrZotov** [comment] 2023-08-21 20:36
✅ Fixed in [Connect v.1.7.2](https://hub.docker.com/layers/1password/connect-api/1.7.2/images/sha256-0c5ae74396e3c18c3b65acb89cb76d31088968cf0c25deca3818c72b01586606?context=explore)

**Closed by volodymyrZotov** 2023-08-21 20:36 UTC
Labels: bug
